// ========================================
// UNDERSTANDING YOUR INVOICE GUIDE - PIXELPERFECT
// ========================================
// File: frontend/src/guides/UnderstandingYourInvoiceGuide.jsx
// Author: OneTechly
// Update: April 28, 2026
//
// Article #27 in "Billing & Subscription" category
// (Slug: understanding-your-invoice in helpArticles.js)
//
// Verified facts:
//   - All invoices generated by Stripe (we're a Stripe customer; Stripe
//     handles tax/proration/PDF generation)
//   - Invoice access via Stripe Customer Portal
//   - Tier names on invoice will show "PixelPerfect Pro" / "Business" /
//     "Premium" + "Monthly" or "Annual"
//   - Tax handled by Stripe Tax based on billing address
//   - PDF copies downloadable from portal
//
// Tone: explanatory, not apologetic. Demystifies a real Stripe invoice
// for users who haven't seen one before, without pretending we control
// formatting elements we don't control.
// ========================================

import React from 'react';

const UnderstandingYourInvoiceGuide = () => {
  return (
    <div className="prose prose-blue max-w-none">
      {/* What you'll learn callout */}
      <div className="bg-blue-50 border-l-4 border-blue-600 p-4 mb-8 rounded">
        <div className="flex items-start gap-3">
          <svg className="w-6 h-6 text-blue-600 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
          </svg>
          <div>
            <h3 className="text-lg font-semibold text-blue-900 mt-0 mb-1">What you'll learn</h3>
            <p className="text-blue-800 text-sm mb-0">
              How to read your PixelPerfect invoice line by line. What proration looks like,
              why tax appears on some invoices and not others, why an invoice might be $0,
              and where to download PDF copies for your records.
            </p>
          </div>
        </div>
      </div>

      {/* Where invoices come from */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Where Your Invoice Comes From</h2>
      <p className="text-gray-700 leading-relaxed">
        Your invoice is generated by Stripe, our payment processor. We're effectively a
        Stripe customer ourselves &mdash; when you upgrade, downgrade, or renew, Stripe creates a
        formal invoice on our behalf, calculates tax, charges your card, and sends you a
        receipt. The invoice is the same format any business using Stripe would send.
      </p>
      <p className="text-gray-700 leading-relaxed mt-3">
        This article walks through the parts of that invoice so you know what each line
        means.
      </p>

      {/* Where to find them */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Where to Find Your Invoices</h2>
      <p className="text-gray-700 leading-relaxed">
        Two places, both showing the same data:
      </p>
      <ul className="space-y-3 mt-4 text-gray-700">
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">1.</span>
          <span>
            <strong>Email.</strong> Stripe emails you a receipt within a few minutes of every
            successful charge. The email contains a link to view the full invoice and
            download a PDF.
          </span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">2.</span>
          <span>
            <strong>Stripe Customer Portal.</strong> From your PixelPerfect dashboard, click
            "Manage Billing" to open the portal. The Invoices section lists every invoice
            (paid, open, draft, or void) with download links.
          </span>
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mt-3">
        Lost the email? The portal has the complete history. There's no time limit &mdash; old
        invoices stay accessible for as long as your Stripe customer record exists.
      </p>

      {/* Anatomy */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Anatomy of a PixelPerfect Invoice</h2>
      <p className="text-gray-700 leading-relaxed">
        A typical invoice looks like this. The exact layout varies slightly by region (EU
        invoices show VAT differently than US invoices), but the same fields are always
        present:
      </p>

      <div className="bg-gray-50 border border-gray-200 rounded-lg p-5 my-4 font-mono text-sm">
        <div className="text-gray-900 font-bold mb-3">Invoice INV-2026-0412</div>
        <div className="border-t border-gray-300 pt-3 space-y-1 text-xs text-gray-700">
          <div className="flex justify-between"><span>Bill to:</span><span>Your billing email</span></div>
          <div className="flex justify-between"><span>Issue date:</span><span>April 12, 2026</span></div>
          <div className="flex justify-between"><span>Due date:</span><span>April 12, 2026 (paid)</span></div>
          <div className="flex justify-between"><span>Period:</span><span>Apr 12, 2026 &ndash; May 12, 2026</span></div>
        </div>
        <div className="border-t border-gray-300 mt-3 pt-3 space-y-1 text-xs text-gray-700">
          <div className="flex justify-between"><span>PixelPerfect Pro &mdash; Monthly</span><span>$49.00</span></div>
          <div className="flex justify-between"><span>Subtotal</span><span>$49.00</span></div>
          <div className="flex justify-between"><span>Tax (if applicable)</span><span>$0.00 &ndash; $X.XX</span></div>
          <div className="flex justify-between font-bold text-gray-900 pt-2 border-t border-gray-300"><span>Total</span><span>$49.00 &ndash; $XX.XX</span></div>
          <div className="flex justify-between text-green-700"><span>Paid (Visa ending 4242)</span><span>&minus;$49.00</span></div>
          <div className="flex justify-between font-bold text-gray-900 pt-2 border-t border-gray-300"><span>Amount due</span><span>$0.00</span></div>
        </div>
      </div>

      {/* Each field explained */}
      <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">Reading each field</h3>
      <ul className="space-y-3 text-gray-700">
        <li>
          <strong>Invoice number.</strong> A unique identifier (e.g., <code className="font-mono">INV-2026-0412</code>).
          Reference this number if you ever need to ask us about a specific charge.
        </li>
        <li>
          <strong>Bill to.</strong> The billing email you provided in Stripe Checkout. This
          can be different from your PixelPerfect login email &mdash; useful when you want
          receipts to go to an accounts-payable address.
        </li>
        <li>
          <strong>Period.</strong> The window of service this invoice covers. For monthly
          subscriptions, it's typically a 30-day window starting from your renewal date.
        </li>
        <li>
          <strong>Line item ("PixelPerfect Pro &mdash; Monthly," etc.).</strong> The name of the
          tier and the billing cadence. If you upgraded mid-cycle, you may see multiple line
          items (one for the unused portion of the old tier as a credit, one for the new
          tier prorated to the end of the period).
        </li>
        <li>
          <strong>Subtotal.</strong> Pre-tax amount. Matches the tier price for full-period
          renewals.
        </li>
        <li>
          <strong>Tax.</strong> Calculated by Stripe Tax based on your billing address. May
          be $0.00 if your jurisdiction doesn't impose sales tax / VAT on this category, or
          if you've provided a valid tax exemption (e.g., EU VAT ID for B2B sales).
        </li>
        <li>
          <strong>Total.</strong> Subtotal plus tax. This is the amount you actually paid.
        </li>
        <li>
          <strong>Paid.</strong> Lists the card or payment method used and confirms the
          charge succeeded. The card is identified by network and last 4 digits only &mdash;
          Stripe never shows the full card number.
        </li>
        <li>
          <strong>Amount due.</strong> $0.00 if the invoice is paid in full. Anything else
          means an outstanding balance &mdash; usually the result of a failed charge.
        </li>
      </ul>

      {/* Proration */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Why You Might See Proration on an Invoice</h2>
      <p className="text-gray-700 leading-relaxed">
        Proration appears when you change tiers mid-cycle. Stripe calculates a credit for the
        unused portion of your previous tier and a charge for the new tier from the change
        date to the end of the period. The math is:
      </p>

      <div className="bg-gray-900 rounded-lg p-4 my-3 overflow-x-auto">
        <pre className="text-green-400 text-sm font-mono">
{`Credit  = old_tier_price × (days_remaining / days_in_period)
Charge  = new_tier_price × (days_remaining / days_in_period)
Net     = Charge − Credit`}
        </pre>
      </div>

      <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">A worked example</h3>
      <p className="text-gray-700 leading-relaxed">
        You're on Pro ($49/month). 10 days into a 30-day cycle, you upgrade to Business
        ($199/month). Your invoice shows two line items:
      </p>

      <div className="bg-gray-50 border border-gray-200 rounded-lg p-5 my-4 font-mono text-sm">
        <div className="space-y-1 text-gray-700">
          <div className="flex justify-between">
            <span>Unused time on Pro &mdash; 20 days credit</span>
            <span>&minus;$32.67</span>
          </div>
          <div className="flex justify-between">
            <span>Remaining time on Business &mdash; 20 days</span>
            <span>$132.67</span>
          </div>
          <div className="flex justify-between font-bold text-gray-900 pt-2 border-t border-gray-300">
            <span>Net charge today</span>
            <span>$100.00</span>
          </div>
        </div>
      </div>

      <p className="text-gray-700 leading-relaxed">
        Your next invoice (30 days later) will be a clean $199 for a full Business month.
        The "messy" prorated invoice happens once, at the moment of the tier change.
      </p>

      {/* $0 invoices */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">"My Invoice Is for $0 &mdash; What Is This?"</h2>
      <p className="text-gray-700 leading-relaxed">
        Stripe sometimes generates a $0 invoice. This is normal and not a billing error. The
        most common causes:
      </p>
      <ul className="space-y-2 mt-3 text-gray-700">
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span><strong>You downgraded mid-cycle.</strong> The credit from the higher tier exactly covered the lower tier through the rest of the period.</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span><strong>You canceled and the credit covered the remaining period.</strong> The invoice closes out your account at zero.</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span><strong>A coupon or credit was applied.</strong> If you have an account credit balance, Stripe applies it before charging your card.</span>
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mt-3">
        $0 invoices still get sent to your billing email and stored in the portal. They're a
        formal record of the service period, just with no money changing hands.
      </p>

      {/* Tax */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Tax on Your Invoice</h2>
      <p className="text-gray-700 leading-relaxed">
        Stripe Tax handles tax calculation based on your billing address. Two common
        situations:
      </p>

      <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">US customers</h3>
      <p className="text-gray-700 leading-relaxed">
        Sales tax depends on your state. SaaS is taxable in some states (New York,
        Washington, Texas, etc.) and not in others. Stripe applies the right rate
        automatically based on the address you provided at checkout.
      </p>

      <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">EU customers</h3>
      <p className="text-gray-700 leading-relaxed">
        VAT is calculated based on your country. For B2B customers with a valid VAT ID, the
        reverse charge mechanism applies (you self-account for VAT) and the invoice shows
        $0 in tax with a note. For B2C customers and B2B customers without a VAT ID, the
        local VAT rate applies.
      </p>

      <h3 className="text-lg font-semibold text-gray-900 mt-6 mb-3">Updating your tax info</h3>
      <p className="text-gray-700 leading-relaxed">
        To add or update your VAT ID, business name, or billing address, open the Stripe
        Customer Portal from your dashboard and edit the billing details. Future invoices
        will reflect the change. Past invoices can be reissued on request &mdash; email{' '}
        <a href="mailto:onetechly@gmail.com?subject=Reissue invoice with updated tax info" className="text-blue-600 hover:underline">
          onetechly@gmail.com
        </a>{' '}
        with the original invoice number.
      </p>

      {/* Refunds on invoices */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">How Refunds Show on Invoices</h2>
      <p className="text-gray-700 leading-relaxed">
        When we issue a refund, you don't get a "negative" invoice. Instead:
      </p>
      <ul className="space-y-2 mt-3 text-gray-700">
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>The original invoice keeps its original total and status.</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>Stripe issues a separate <strong>refund</strong> against the original charge.</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>The refund appears in your card statement within 5&ndash;10 business days.</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>You'll get a refund receipt email separately from the original invoice email.</span>
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mt-3">
        See the <a href="/help/article/cancellation-and-refunds" className="text-blue-600 hover:underline">
          Cancellation and Refunds guide
        </a>{' '}
        for the full refund policy.
      </p>

      {/* Common scenarios */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Common Scenarios</h2>

      <div className="space-y-4">
        <div className="bg-white border border-gray-200 rounded-lg p-5">
          <h4 className="font-semibold text-gray-900 mb-2">"I need to download an invoice as a PDF for my accountant"</h4>
          <p className="text-sm text-gray-700">
            Open the Stripe Customer Portal from your dashboard. The Invoices section has a
            download icon next to each invoice that gives you a PDF copy. The PDF includes
            all the same fields you see in the portal, formatted for printing.
          </p>
        </div>

        <div className="bg-white border border-gray-200 rounded-lg p-5">
          <h4 className="font-semibold text-gray-900 mb-2">"I need my company name on the invoice instead of my personal name"</h4>
          <p className="text-sm text-gray-700">
            Open the Stripe portal, edit the billing details, and add your company name. New
            invoices will reflect the change. For past invoices, email us with the invoice
            numbers and we can reissue them with the corrected company name.
          </p>
        </div>

        <div className="bg-white border border-gray-200 rounded-lg p-5">
          <h4 className="font-semibold text-gray-900 mb-2">"I see an invoice marked 'Open' that I don't remember"</h4>
          <p className="text-sm text-gray-700">
            "Open" means Stripe issued the invoice but the charge hasn't completed yet. Most
            commonly: a recent renewal where your card failed and Stripe is in the dunning
            retry window. Check the email Stripe sent &mdash; it'll tell you the failure reason
            and what to do.
          </p>
        </div>

        <div className="bg-white border border-gray-200 rounded-lg p-5">
          <h4 className="font-semibold text-gray-900 mb-2">"The amount on my card statement doesn't match the invoice"</h4>
          <p className="text-sm text-gray-700">
            Most often, this is a currency conversion fee from your bank if you're paying in
            a non-USD currency &mdash; the bank's conversion rate plus any foreign-transaction fee
            adds a few cents to dollars. The invoice shows what we charged in USD; your bank
            converted to your local currency at their rate.
          </p>
        </div>

        <div className="bg-white border border-gray-200 rounded-lg p-5">
          <h4 className="font-semibold text-gray-900 mb-2">"I'm being charged tax I don't think should apply"</h4>
          <p className="text-sm text-gray-700">
            This usually means your billing address in Stripe is in a jurisdiction that taxes
            SaaS, or your VAT ID isn't on file (for EU B2B). Update your billing details in
            the Stripe portal and email us &mdash; we can reissue the most recent invoice with
            the corrected tax treatment.
          </p>
        </div>
      </div>

      {/* When to contact support */}
      <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">When to Contact Support</h2>
      <p className="text-gray-700 leading-relaxed">
        Email <a href="mailto:onetechly@gmail.com?subject=Invoice question" className="text-blue-600 hover:underline">
          onetechly@gmail.com
        </a>{' '}
        if any of the following are true:
      </p>
      <ul className="space-y-2 mt-3 text-gray-700">
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>An invoice amount looks wrong and the explanations above don't match your situation</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>You need an invoice reissued with corrected company name, VAT ID, or address</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>You see a charge on your card you don't recognize</span>
        </li>
        <li className="flex items-start gap-2">
          <span className="text-blue-600 font-bold mt-0.5">&bull;</span>
          <span>You need a custom invoice format your accounting team requires</span>
        </li>
      </ul>
      <p className="text-gray-700 leading-relaxed mt-3">
        Include the invoice number in your email &mdash; that's the fastest way for us to
        identify exactly what you're asking about.
      </p>

      {/* Next Steps */}
      <h2 className="text-2xl font-bold text-gray-900 mt-10 mb-4">Next Steps</h2>

      <div className="grid grid-cols-1 gap-4">
        <a
          href="/help/article/managing-payment-methods"
          className="flex items-center justify-between p-4 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors no-underline"
        >
          <div>
            <h4 className="font-semibold text-blue-900 mb-1">Managing Payment Methods</h4>
            <p className="text-sm text-blue-700 mb-0">Add, update, or remove cards through the Stripe Customer Portal</p>
          </div>
          <svg className="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </a>

        <a
          href="/help/article/cancellation-and-refunds"
          className="flex items-center justify-between p-4 bg-amber-50 hover:bg-amber-100 rounded-lg transition-colors no-underline"
        >
          <div>
            <h4 className="font-semibold text-amber-900 mb-1">Cancellation and Refunds</h4>
            <p className="text-sm text-amber-700 mb-0">How refund requests are processed and how they appear in your records</p>
          </div>
          <svg className="w-6 h-6 text-amber-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </a>

        <a
          href="/help/article/understanding-pricing-plans"
          className="flex items-center justify-between p-4 bg-purple-50 hover:bg-purple-100 rounded-lg transition-colors no-underline"
        >
          <div>
            <h4 className="font-semibold text-purple-900 mb-1">Understanding Pricing Plans</h4>
            <p className="text-sm text-purple-700 mb-0">Compare tiers and pick the right one for your usage pattern</p>
          </div>
          <svg className="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
          </svg>
        </a>
      </div>

      {/* Success footer */}
      <div className="bg-green-50 border-l-4 border-green-500 p-4 mt-8 rounded">
        <div className="flex items-start gap-3">
          <svg className="w-6 h-6 text-green-600 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
          </svg>
          <div>
            <h4 className="text-sm font-semibold text-green-900 mt-0 mb-1">Invoice decoded 📄</h4>
            <p className="text-green-800 text-sm mb-0">
              You can read every line on your PixelPerfect invoice, recognize proration math
              when it shows up, understand why a $0 invoice exists, and find PDFs in the
              Stripe Customer Portal. For anything that doesn't match the patterns here,
              email support with the invoice number and we'll explain.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default UnderstandingYourInvoiceGuide;

//=====END OF UnderstandingYourInvoiceGuide =====